---
- name: Ping Test Playbook
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Define a list of new hosts with their groups and credentials
      set_fact:
        new_hosts:
          - hostname: 192.168.10.3
            group: routers

    - name: Add new hosts to inventory
      add_host:
        name: "{{ item.hostname }}"
        groups: "{{ item.group }}"
      loop: "{{ new_hosts }}"

- name: Perform tasks on routers
  hosts: routers
  gather_facts: no
  vars:
    ansible_user: "sreram"
    ansible_ssh_pass: "Saibaba@007"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_ssh_common_args: '-o KexAlgorithms=diffie-hellman-group14-sha1'
  tasks:
    - name: Ensure the target hosts are reachable
      wait_for_connection:
        timeout: 10

    - name: Get facts from Cisco IOS devices
      cisco.ios.ios_facts:
      register: cisco_facts

    - name: Display gathered facts
      ansible.builtin.debug:
        var: cisco_facts

    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
      register: version_output

    - name: Display show version output
      ansible.builtin.debug:
        var: version_output
